root: true

parser: babel-eslint

parserOptions:
  ecmaVersion: 2018

extends: [
  "react-app",
  "eslint-config-prettier"
]

env:
  browser: true
  es6: true
  jest: true
  node: true

globals:
  enzymeToJson: true
  mount: true
  render: true
  shallow: true

rules:
  semi: off
